INSERT INTO badges (id, title, description, icon_svg) VALUES
('ambrose_a_call_state_park_state_park', 'Ambrose A. Call State Park', 'Hiked 3 trails at Ambrose A. Call State Park', 'IA'),
('backbone_state_park_state_park', 'Backbone State Park', 'Hiked 3 trails at Backbone State Park', 'IA'),
('badger_creek_state_recreation_area_state_park', 'Badger Creek State Recreation Area', 'Hiked 3 trails at Badger Creek State Recreation Area', 'IA'),
('banner_lakes_at_summerset_state_park_state_park', 'Banner Lakes at Summerset State Park', 'Hiked 3 trails at Banner Lakes at Summerset State Park', 'IA'),
('beeds_lake_state_park_state_park', 'Beed''s Lake State Park', 'Hiked 3 trails at Beed''s Lake State Park', 'IA'),
('bellevue_state_park_state_park', 'Bellevue State Park', 'Hiked 3 trails at Bellevue State Park', 'IA'),
('big_creek_state_park_state_park', 'Big Creek State Park', 'Hiked 3 trails at Big Creek State Park', 'IA'),
('black_hawk_state_park_state_park', 'Black Hawk State Park', 'Hiked 3 trails at Black Hawk State Park', 'IA'),
('brushy_creek_state_recreation_area_state_park', 'Brushy Creek State Recreation Area', 'Hiked 3 trails at Brushy Creek State Recreation Area', 'IA'),
('cedar_rock_state_park_state_park', 'Cedar Rock State Park', 'Hiked 3 trails at Cedar Rock State Park', 'IA'),
('clear_lake_state_park_state_park', 'Clear Lake State Park', 'Hiked 3 trails at Clear Lake State Park', 'IA'),
('dolliver_memorial_state_park_state_park', 'Dolliver Memorial State Park', 'Hiked 3 trails at Dolliver Memorial State Park', 'IA'),
('elinor_bedell_state_park_state_park', 'Elinor Bedell State Park', 'Hiked 3 trails at Elinor Bedell State Park', 'IA'),
('elk_rock_state_park_state_park', 'Elk Rock State Park', 'Hiked 3 trails at Elk Rock State Park', 'IA'),
('emerson_bay_state_recreation_area_state_park', 'Emerson Bay State Recreation Area', 'Hiked 3 trails at Emerson Bay State Recreation Area', 'IA'),
('fairport_state_recreation_area_state_park', 'Fairport State Recreation Area', 'Hiked 3 trails at Fairport State Recreation Area', 'IA'),
('fort_atkinson_state_preserve_state_park', 'Fort Atkinson State Preserve', 'Hiked 3 trails at Fort Atkinson State Preserve', 'IA'),
('fort_defiance_state_park_state_park', 'Fort Defiance State Park', 'Hiked 3 trails at Fort Defiance State Park', 'IA'),
('geode_state_park_state_park', 'Geode State Park', 'Hiked 3 trails at Geode State Park', 'IA'),
('george_wyth_memorial_state_park_state_park', 'George Wyth Memorial State Park', 'Hiked 3 trails at George Wyth Memorial State Park', 'IA'),
('green_valley_state_park_state_park', 'Green Valley State Park', 'Hiked 3 trails at Green Valley State Park', 'IA'),
('gull_point_state_park_state_park', 'Gull Point State Park', 'Hiked 3 trails at Gull Point State Park', 'IA'),
('honey_creek_state_park_state_park', 'Honey Creek State Park', 'Hiked 3 trails at Honey Creek State Park', 'IA'),
('honey_creek_resort_state_park_state_park', 'Honey Creek Resort State Park', 'Hiked 3 trails at Honey Creek Resort State Park', 'IA'),
('laceykeosauqua_state_park_state_park', 'Lacey-Keosauqua State Park', 'Hiked 3 trails at Lacey-Keosauqua State Park', 'IA'),
('lake_ahquabi_state_park_state_park', 'Lake Ahquabi State Park', 'Hiked 3 trails at Lake Ahquabi State Park', 'IA'),
('lake_anita_state_park_state_park', 'Lake Anita State Park', 'Hiked 3 trails at Lake Anita State Park', 'IA'),
('lake_darling_state_park_state_park', 'Lake Darling State Park', 'Hiked 3 trails at Lake Darling State Park', 'IA'),
('lake_keomah_state_park_state_park', 'Lake Keomah State Park', 'Hiked 3 trails at Lake Keomah State Park', 'IA'),
('lake_macbride_state_park_state_park', 'Lake Macbride State Park', 'Hiked 3 trails at Lake Macbride State Park', 'IA'),
('lake_manawa_state_park_state_park', 'Lake Manawa State Park', 'Hiked 3 trails at Lake Manawa State Park', 'IA'),
('lake_of_three_fires_state_park_state_park', 'Lake of Three Fires State Park', 'Hiked 3 trails at Lake of Three Fires State Park', 'IA'),
('lake_wapello_state_park_state_park', 'Lake Wapello State Park', 'Hiked 3 trails at Lake Wapello State Park', 'IA'),
('ledges_state_park_state_park', 'Ledges State Park', 'Hiked 3 trails at Ledges State Park', 'IA'),
('lewis_and_clark_state_park_state_park', 'Lewis and Clark State Park', 'Hiked 3 trails at Lewis and Clark State Park', 'IA'),
('lower_gar_state_recreation_area_state_park', 'Lower Gar State Recreation Area', 'Hiked 3 trails at Lower Gar State Recreation Area', 'IA'),
('maquoketa_caves_state_park_state_park', 'Maquoketa Caves State Park', 'Hiked 3 trails at Maquoketa Caves State Park', 'IA'),
('marble_beach_state_recreation_area_state_park', 'Marble Beach State Recreation Area', 'Hiked 3 trails at Marble Beach State Recreation Area', 'IA'),
('mcintosh_woods_state_park_state_park', 'McIntosh Woods State Park', 'Hiked 3 trails at McIntosh Woods State Park', 'IA'),
('mines_of_spain_state_recreation_area_and_e_b_lyons_nature_center_state_park', 'Mines of Spain State Recreation Area and E. B. Lyons Nature Center', 'Hiked 3 trails at Mines of Spain State Recreation Area and E. B. Lyons Nature Center', 'IA'),
('miniwakan_state_park_state_park', 'Mini-Wakan State Park', 'Hiked 3 trails at Mini-Wakan State Park', 'IA'),
('nine_eagles_state_park_state_park', 'Nine Eagles State Park', 'Hiked 3 trails at Nine Eagles State Park', 'IA'),
('okamanpedan_state_park_state_park', 'Okamanpedan State Park', 'Hiked 3 trails at Okamanpedan State Park', 'IA'),
('palisadeskepler_state_park_state_park', 'Palisades-Kepler State Park', 'Hiked 3 trails at Palisades-Kepler State Park', 'IA'),
('pikes_peak_state_park_state_park', 'Pikes Peak State Park', 'Hiked 3 trails at Pikes Peak State Park', 'IA'),
('pikes_point_state_park_state_park', 'Pikes Point State Park', 'Hiked 3 trails at Pikes Point State Park', 'IA'),
('pilot_knob_state_park_state_park', 'Pilot Knob State Park', 'Hiked 3 trails at Pilot Knob State Park', 'IA'),
('pine_lake_state_park_state_park', 'Pine Lake State Park', 'Hiked 3 trails at Pine Lake State Park', 'IA'),
('pleasant_creek_state_recreation_area_state_park', 'Pleasant Creek State Recreation Area', 'Hiked 3 trails at Pleasant Creek State Recreation Area', 'IA'),
('prairie_rose_state_park_state_park', 'Prairie Rose State Park', 'Hiked 3 trails at Prairie Rose State Park', 'IA'),
('preparation_canyon_state_park_state_park', 'Preparation Canyon State Park', 'Hiked 3 trails at Preparation Canyon State Park', 'IA'),
('red_haw_state_park_state_park', 'Red Haw State Park', 'Hiked 3 trails at Red Haw State Park', 'IA'),
('rice_lake_state_park_state_park', 'Rice Lake State Park', 'Hiked 3 trails at Rice Lake State Park', 'IA'),
('rock_creek_state_park_state_park', 'Rock Creek State Park', 'Hiked 3 trails at Rock Creek State Park', 'IA'),
('springbrook_state_park_state_park', 'Springbrook State Park', 'Hiked 3 trails at Springbrook State Park', 'IA'),
('stone_state_park_state_park', 'Stone State Park', 'Hiked 3 trails at Stone State Park', 'IA'),
('templar_state_recreation_area_state_park', 'Templar State Recreation Area', 'Hiked 3 trails at Templar State Recreation Area', 'IA'),
('trappers_bay_state_park_state_park', 'Trapper''s Bay State Park', 'Hiked 3 trails at Trapper''s Bay State Park', 'IA'),
('twin_lakes_state_park_state_park', 'Twin Lakes State Park', 'Hiked 3 trails at Twin Lakes State Park', 'IA'),
('union_grove_state_park_state_park', 'Union Grove State Park', 'Hiked 3 trails at Union Grove State Park', 'IA'),
('viking_lake_state_park_state_park', 'Viking Lake State Park', 'Hiked 3 trails at Viking Lake State Park', 'IA'),
('volga_river_state_recreation_area_state_park', 'Volga River State Recreation Area', 'Hiked 3 trails at Volga River State Recreation Area', 'IA'),
('walnut_woods_state_park_state_park', 'Walnut Woods State Park', 'Hiked 3 trails at Walnut Woods State Park', 'IA'),
('wapsipinicon_state_park_state_park', 'Wapsipinicon State Park', 'Hiked 3 trails at Wapsipinicon State Park', 'IA'),
('waubonsie_state_park_state_park', 'Waubonsie State Park', 'Hiked 3 trails at Waubonsie State Park', 'IA'),
('wildcat_den_state_park_state_park', 'Wildcat Den State Park', 'Hiked 3 trails at Wildcat Den State Park', 'IA'),
('wilson_island_state_recreation_area_state_park', 'Wilson Island State Recreation Area', 'Hiked 3 trails at Wilson Island State Recreation Area', 'IA'),
('bobwhite_state_park_state_park', 'Bobwhite State Park', 'Hiked 3 trails at Bobwhite State Park', 'IA'),
('cold_springs_state_park_state_park', 'Cold Springs State Park', 'Hiked 3 trails at Cold Springs State Park', 'IA'),
('crystal_lake_state_park_state_park', 'Crystal Lake State Park', 'Hiked 3 trails at Crystal Lake State Park', 'IA'),
('eagle_lake_state_park_state_park', 'Eagle Lake State Park', 'Hiked 3 trails at Eagle Lake State Park', 'IA'),
('echo_valley_state_park_state_park', 'Echo Valley State Park', 'Hiked 3 trails at Echo Valley State Park', 'IA'),
('frank_a_gotch_state_park_state_park', 'Frank A. Gotch State Park', 'Hiked 3 trails at Frank A. Gotch State Park', 'IA'),
('heery_woods_state_park_state_park', 'Heery Woods State Park', 'Hiked 3 trails at Heery Woods State Park', 'IA'),
('kearny_state_park_state_park', 'Kearny State Park', 'Hiked 3 trails at Kearny State Park', 'IA'),
('lake_cornelia_state_park_state_park', 'Lake Cornelia State Park', 'Hiked 3 trails at Lake Cornelia State Park', 'IA'),
('lake_icaria_state_park_state_park', 'Lake Icaria State Park', 'Hiked 3 trails at Lake Icaria State Park', 'IA'),
('margo_frankel_state_park_state_park', 'Margo Frankel State Park', 'Hiked 3 trails at Margo Frankel State Park', 'IA'),
('mill_creek_state_park_state_park', 'Mill Creek State Park', 'Hiked 3 trails at Mill Creek State Park', 'IA'),
('oak_grove_state_park_state_park', 'Oak Grove State Park', 'Hiked 3 trails at Oak Grove State Park', 'IA'),
('oakland_mills_state_park_state_park', 'Oakland Mills State Park', 'Hiked 3 trails at Oakland Mills State Park', 'IA'),
('pammel_state_park_state_park', 'Pammel State Park', 'Hiked 3 trails at Pammel State Park', 'IA'),
('sharon_bluffs_state_park_state_park', 'Sharon Bluffs State Park', 'Hiked 3 trails at Sharon Bluffs State Park', 'IA'),
('spring_lake_state_park_state_park', 'Spring Lake State Park', 'Hiked 3 trails at Spring Lake State Park', 'IA'),
('swan_lake_state_park_state_park', 'Swan Lake State Park', 'Hiked 3 trails at Swan Lake State Park', 'IA'),
('three_mile_lake_state_park_state_park', 'Three Mile Lake State Park', 'Hiked 3 trails at Three Mile Lake State Park', 'IA'),
('chadron_state_park_state_park', 'Chadron State Park', 'Hiked 3 trails at Chadron State Park', 'NE'),
('eugene_t_mahoney_state_park_state_park', 'Eugene T. Mahoney State Park', 'Hiked 3 trails at Eugene T. Mahoney State Park', 'NE'),
('fort_robinson_state_park_state_park', 'Fort Robinson State Park', 'Hiked 3 trails at Fort Robinson State Park', 'NE'),
('indian_cave_state_park_state_park', 'Indian Cave State Park', 'Hiked 3 trails at Indian Cave State Park', 'NE'),
('niobrara_state_park_state_park', 'Niobrara State Park', 'Hiked 3 trails at Niobrara State Park', 'NE'),
('platte_river_state_park_state_park', 'Platte River State Park', 'Hiked 3 trails at Platte River State Park', 'NE'),
('ponca_state_park_state_park', 'Ponca State Park', 'Hiked 3 trails at Ponca State Park', 'NE'),
('smith_falls_state_park_state_park', 'Smith Falls State Park', 'Hiked 3 trails at Smith Falls State Park', 'NE'),
('arbor_lodge_state_historical_park_state_park', 'Arbor Lodge State Historical Park', 'Hiked 3 trails at Arbor Lodge State Historical Park', 'NE'),
('ash_hollow_state_historical_park_state_park', 'Ash Hollow State Historical Park', 'Hiked 3 trails at Ash Hollow State Historical Park', 'NE'),
('ashfall_fossil_beds_state_historical_park_state_park', 'Ashfall Fossil Beds State Historical Park', 'Hiked 3 trails at Ashfall Fossil Beds State Historical Park', 'NE'),
('bowring_ranch_state_historical_park_state_park', 'Bowring Ranch State Historical Park', 'Hiked 3 trails at Bowring Ranch State Historical Park', 'NE'),
('buffalo_bill_ranch_state_historical_park_state_park', 'Buffalo Bill Ranch State Historical Park', 'Hiked 3 trails at Buffalo Bill Ranch State Historical Park', 'NE'),
('fort_atkinson_state_historical_park_state_park', 'Fort Atkinson State Historical Park', 'Hiked 3 trails at Fort Atkinson State Historical Park', 'NE'),
('fort_hartsuff_state_historical_park_state_park', 'Fort Hartsuff State Historical Park', 'Hiked 3 trails at Fort Hartsuff State Historical Park', 'NE'),
('fort_kearny_state_historical_park_state_park', 'Fort Kearny State Historical Park', 'Hiked 3 trails at Fort Kearny State Historical Park', 'NE'),
('rock_creek_station_state_historical_park_state_park', 'Rock Creek Station State Historical Park', 'Hiked 3 trails at Rock Creek Station State Historical Park', 'NE'),
('ahern_state_park_state_park', 'Ahern State Park', 'Hiked 3 trails at Ahern State Park', 'NH'),
('androscoggin_wayside_park_state_park', 'Androscoggin Wayside Park', 'Hiked 3 trails at Androscoggin Wayside Park', 'NH'),
('bear_brook_state_park_state_park', 'Bear Brook State Park', 'Hiked 3 trails at Bear Brook State Park', 'NH'),
('beaver_brook_falls_wayside_state_park', 'Beaver Brook Falls Wayside', 'Hiked 3 trails at Beaver Brook Falls Wayside', 'NH'),
('cardigan_mountain_state_park_state_park', 'Cardigan Mountain State Park', 'Hiked 3 trails at Cardigan Mountain State Park', 'NH'),
('chesterfield_gorge_natural_area_state_park', 'Chesterfield Gorge Natural Area', 'Hiked 3 trails at Chesterfield Gorge Natural Area', 'NH'),
('clough_state_park_state_park', 'Clough State Park', 'Hiked 3 trails at Clough State Park', 'NH'),
('coleman_state_park_state_park', 'Coleman State Park', 'Hiked 3 trails at Coleman State Park', 'NH'),
('crawford_notch_state_park_state_park', 'Crawford Notch State Park', 'Hiked 3 trails at Crawford Notch State Park', 'NH'),
('deer_mountain_campground_state_park', 'Deer Mountain Campground', 'Hiked 3 trails at Deer Mountain Campground', 'NH'),
('dixville_notch_state_park_state_park', 'Dixville Notch State Park', 'Hiked 3 trails at Dixville Notch State Park', 'NH'),
('echo_lake_state_park_state_park', 'Echo Lake State Park', 'Hiked 3 trails at Echo Lake State Park', 'NH'),
('eisenhower_memorial_wayside_park_state_park', 'Eisenhower Memorial Wayside Park', 'Hiked 3 trails at Eisenhower Memorial Wayside Park', 'NH'),
('ellacoya_state_park_state_park', 'Ellacoya State Park', 'Hiked 3 trails at Ellacoya State Park', 'NH'),
('forest_lake_state_park_state_park', 'Forest Lake State Park', 'Hiked 3 trails at Forest Lake State Park', 'NH'),
('franconia_notch_state_park_state_park', 'Franconia Notch State Park', 'Hiked 3 trails at Franconia Notch State Park', 'NH'),
('gardner_memorial_wayside_park_state_park', 'Gardner Memorial Wayside Park', 'Hiked 3 trails at Gardner Memorial Wayside Park', 'NH'),
('greenfield_state_park_state_park', 'Greenfield State Park', 'Hiked 3 trails at Greenfield State Park', 'NH'),
('hampton_beach_state_park_state_park', 'Hampton Beach State Park', 'Hiked 3 trails at Hampton Beach State Park', 'NH'),
('jenness_state_beach_state_park', 'Jenness State Beach', 'Hiked 3 trails at Jenness State Beach', 'NH'),
('jericho_mountain_state_park_state_park', 'Jericho Mountain State Park', 'Hiked 3 trails at Jericho Mountain State Park', 'NH'),
('kingston_state_park_state_park', 'Kingston State Park', 'Hiked 3 trails at Kingston State Park', 'NH'),
('lake_francis_state_park_state_park', 'Lake Francis State Park', 'Hiked 3 trails at Lake Francis State Park', 'NH'),
('lake_tarleton_state_park_state_park', 'Lake Tarleton State Park', 'Hiked 3 trails at Lake Tarleton State Park', 'NH'),
('madison_boulder_natural_area_state_park', 'Madison Boulder Natural Area', 'Hiked 3 trails at Madison Boulder Natural Area', 'NH'),
('milan_hill_state_park_state_park', 'Milan Hill State Park', 'Hiked 3 trails at Milan Hill State Park', 'NH'),
('miller_state_park_state_park', 'Miller State Park', 'Hiked 3 trails at Miller State Park', 'NH'),
('mollidgewock_state_park_state_park', 'Mollidgewock State Park', 'Hiked 3 trails at Mollidgewock State Park', 'NH'),
('monadnock_state_park_state_park', 'Monadnock State Park', 'Hiked 3 trails at Monadnock State Park', 'NH'),
('moose_brook_state_park_state_park', 'Moose Brook State Park', 'Hiked 3 trails at Moose Brook State Park', 'NH'),
('mount_sunapee_state_park_state_park', 'Mount Sunapee State Park', 'Hiked 3 trails at Mount Sunapee State Park', 'NH'),
('mount_washington_state_park_state_park', 'Mount Washington State Park', 'Hiked 3 trails at Mount Washington State Park', 'NH'),
('nansen_wayside_park_state_park', 'Nansen Wayside Park', 'Hiked 3 trails at Nansen Wayside Park', 'NH'),
('north_hampton_state_beach_state_park', 'North Hampton State Beach', 'Hiked 3 trails at North Hampton State Beach', 'NH'),
('northwood_meadows_state_park_state_park', 'Northwood Meadows State Park', 'Hiked 3 trails at Northwood Meadows State Park', 'NH'),
('odiorne_point_state_park_state_park', 'Odiorne Point State Park', 'Hiked 3 trails at Odiorne Point State Park', 'NH'),
('pawtuckaway_state_park_state_park', 'Pawtuckaway State Park', 'Hiked 3 trails at Pawtuckaway State Park', 'NH'),
('pillsbury_state_park_state_park', 'Pillsbury State Park', 'Hiked 3 trails at Pillsbury State Park', 'NH'),
('pisgah_state_park_state_park', 'Pisgah State Park', 'Hiked 3 trails at Pisgah State Park', 'NH'),
('rhododendron_state_park_state_park', 'Rhododendron State Park', 'Hiked 3 trails at Rhododendron State Park', 'NH'),
('rollins_state_park_state_park', 'Rollins State Park', 'Hiked 3 trails at Rollins State Park', 'NH'),
('rye_harbor_state_park_state_park', 'Rye Harbor State Park', 'Hiked 3 trails at Rye Harbor State Park', 'NH'),
('sculptured_rocks_natural_area_state_park', 'Sculptured Rocks Natural Area', 'Hiked 3 trails at Sculptured Rocks Natural Area', 'NH'),
('silver_lake_state_park_state_park', 'Silver Lake State Park', 'Hiked 3 trails at Silver Lake State Park', 'NH'),
('umbagog_lake_state_park_state_park', 'Umbagog Lake State Park', 'Hiked 3 trails at Umbagog Lake State Park', 'NH'),
('wadleigh_state_park_state_park', 'Wadleigh State Park', 'Hiked 3 trails at Wadleigh State Park', 'NH'),
('wallis_sands_state_beach_state_park', 'Wallis Sands State Beach', 'Hiked 3 trails at Wallis Sands State Beach', 'NH'),
('weeks_state_park_state_park', 'Weeks State Park', 'Hiked 3 trails at Weeks State Park', 'NH'),
('wellington_state_park_state_park', 'Wellington State Park', 'Hiked 3 trails at Wellington State Park', 'NH'),
('wentworth_state_park_state_park', 'Wentworth State Park', 'Hiked 3 trails at Wentworth State Park', 'NH'),
('white_lake_state_park_state_park', 'White Lake State Park', 'Hiked 3 trails at White Lake State Park', 'NH'),
('winslow_state_park_state_park', 'Winslow State Park', 'Hiked 3 trails at Winslow State Park', 'NH'),
('bedell_bridge_state_historic_site_state_park', 'Bedell Bridge State Historic Site', 'Hiked 3 trails at Bedell Bridge State Historic Site', 'NH'),
('daniel_webster_birthplace_state_historic_site_state_park', 'Daniel Webster Birthplace State Historic Site', 'Hiked 3 trails at Daniel Webster Birthplace State Historic Site', 'NH'),
('endicott_rock_state_historic_site_state_park', 'Endicott Rock State Historic Site', 'Hiked 3 trails at Endicott Rock State Historic Site', 'NH'),
('fort_constitution_state_historic_site_state_park', 'Fort Constitution State Historic Site', 'Hiked 3 trails at Fort Constitution State Historic Site', 'NH'),
('fort_stark_state_historic_site_state_park', 'Fort Stark State Historic Site', 'Hiked 3 trails at Fort Stark State Historic Site', 'NH'),
('franklin_pierce_homestead_state_historic_site_state_park', 'Franklin Pierce Homestead State Historic Site', 'Hiked 3 trails at Franklin Pierce Homestead State Historic Site', 'NH'),
('governor_wentworth_historic_site_state_park', 'Governor Wentworth Historic Site', 'Hiked 3 trails at Governor Wentworth Historic Site', 'NH'),
('hannah_duston_memorial_state_historic_site_state_park', 'Hannah Duston Memorial State Historic Site', 'Hiked 3 trails at Hannah Duston Memorial State Historic Site', 'NH'),
('john_wingate_weeks_historic_site_state_park', 'John Wingate Weeks Historic Site', 'Hiked 3 trails at John Wingate Weeks Historic Site', 'NH'),
('nansen_ski_jump_state_historic_site_state_park', 'Nansen Ski Jump State Historic Site', 'Hiked 3 trails at Nansen Ski Jump State Historic Site', 'NH'),
('robert_frost_farm_state_historic_site_state_park', 'Robert Frost Farm State Historic Site', 'Hiked 3 trails at Robert Frost Farm State Historic Site', 'NH'),
('taylor_mill_state_historic_site_state_park', 'Taylor Mill State Historic Site', 'Hiked 3 trails at Taylor Mill State Historic Site', 'NH'),
('tiptop_house_state_park', 'Tip-Top House', 'Hiked 3 trails at Tip-Top House', 'NH'),
('wentworthcoolidge_mansion_state_historic_site_state_park', 'Wentworth–Coolidge Mansion State Historic Site', 'Hiked 3 trails at Wentworth–Coolidge Mansion State Historic Site', 'NH'),
('white_island_state_historic_site_state_park', 'White Island State Historic Site', 'Hiked 3 trails at White Island State Historic Site', 'NH'),
('willey_house_state_park', 'Willey House', 'Hiked 3 trails at Willey House', 'NH'),
('bears_den_natural_area_state_park', 'Bear''s Den Natural Area', 'Hiked 3 trails at Bear''s Den Natural Area', 'NH'),
('binney_pond_natural_area_state_park', 'Binney Pond Natural Area', 'Hiked 3 trails at Binney Pond Natural Area', 'NH'),
('bradford_pines_natural_area_state_park', 'Bradford Pines Natural Area', 'Hiked 3 trails at Bradford Pines Natural Area', 'NH'),
('crosby_mountain_state_park_state_park', 'Crosby Mountain State Park', 'Hiked 3 trails at Crosby Mountain State Park', 'NH'),
('curtiss_dogwood_natural_area_state_park', 'Curtiss Dogwood Natural Area', 'Hiked 3 trails at Curtiss Dogwood Natural Area', 'NH'),
('dublin_lake_scenic_area_state_park', 'Dublin Lake Scenic Area', 'Hiked 3 trails at Dublin Lake Scenic Area', 'NH'),
('heath_pond_bog_natural_area_state_park', 'Heath Pond Bog Natural Area', 'Hiked 3 trails at Heath Pond Bog Natural Area', 'NH'),
('humphreys_ledge_natural_area_state_park', 'Humphrey''s Ledge Natural Area', 'Hiked 3 trails at Humphrey''s Ledge Natural Area', 'NH'),
('jeremy_mill_natural_area_state_park', 'Jeremy Mill Natural Area', 'Hiked 3 trails at Jeremy Mill Natural Area', 'NH'),
('mascot_mine_natural_area_state_park', 'Mascot Mine Natural Area', 'Hiked 3 trails at Mascot Mine Natural Area', 'NH'),
('ossipee_lake_natural_area_state_park', 'Ossipee Lake Natural Area', 'Hiked 3 trails at Ossipee Lake Natural Area', 'NH'),
('otter_brook_lake_state_park', 'Otter Brook Lake', 'Hiked 3 trails at Otter Brook Lake', 'NH'),
('smiths_ferry_heritage_park_state_park', 'Smith''s Ferry Heritage Park', 'Hiked 3 trails at Smith''s Ferry Heritage Park', 'NH'),
('urban_forestry_center_state_park', 'Urban Forestry Center', 'Hiked 3 trails at Urban Forestry Center', 'NH'),
('wantastiquet_mountain_natural_area_or_wantastiquet_state_forest_state_park', 'Wantastiquet Mountain Natural Area or Wantastiquet State Forest', 'Hiked 3 trails at Wantastiquet Mountain Natural Area or Wantastiquet State Forest', 'NH'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('_state_park', '-', 'Hiked 3 trails at -', 'NJ'),
('bluewater_lake_state_park_state_park', 'Bluewater Lake State Park', 'Hiked 3 trails at Bluewater Lake State Park', 'NM'),
('bottomless_lakes_state_park_state_park', 'Bottomless Lakes State Park', 'Hiked 3 trails at Bottomless Lakes State Park', 'NM'),
('brantley_lake_state_park_state_park', 'Brantley Lake State Park', 'Hiked 3 trails at Brantley Lake State Park', 'NM'),
('caballo_lake_state_park_state_park', 'Caballo Lake State Park', 'Hiked 3 trails at Caballo Lake State Park', 'NM'),
('cerrillos_hills_state_park_state_park', 'Cerrillos Hills State Park', 'Hiked 3 trails at Cerrillos Hills State Park', 'NM'),
('cimarron_canyon_state_park_state_park', 'Cimarron Canyon State Park', 'Hiked 3 trails at Cimarron Canyon State Park', 'NM'),
('city_of_rocks_state_park_state_park', 'City of Rocks State Park', 'Hiked 3 trails at City of Rocks State Park', 'NM'),
('clayton_lake_state_park_state_park', 'Clayton Lake State Park', 'Hiked 3 trails at Clayton Lake State Park', 'NM'),
('conchas_lake_state_park_state_park', 'Conchas Lake State Park', 'Hiked 3 trails at Conchas Lake State Park', 'NM'),
('coyote_creek_state_park_state_park', 'Coyote Creek State Park', 'Hiked 3 trails at Coyote Creek State Park', 'NM'),
('eagle_nest_lake_state_park_state_park', 'Eagle Nest Lake State Park', 'Hiked 3 trails at Eagle Nest Lake State Park', 'NM'),
('elephant_butte_lake_state_park_state_park', 'Elephant Butte Lake State Park', 'Hiked 3 trails at Elephant Butte Lake State Park', 'NM'),
('el_vado_lake_state_park_state_park', 'El Vado Lake State Park', 'Hiked 3 trails at El Vado Lake State Park', 'NM'),
('fenton_lake_state_park_state_park', 'Fenton Lake State Park', 'Hiked 3 trails at Fenton Lake State Park', 'NM'),
('heron_lake_state_park_state_park', 'Heron Lake State Park', 'Hiked 3 trails at Heron Lake State Park', 'NM'),
('hyde_memorial_state_park_state_park', 'Hyde Memorial State Park', 'Hiked 3 trails at Hyde Memorial State Park', 'NM'),
('leasburg_dam_state_park_state_park', 'Leasburg Dam State Park', 'Hiked 3 trails at Leasburg Dam State Park', 'NM'),
('living_desert_zoo_and_gardens_state_park_state_park', 'Living Desert Zoo and Gardens State Park', 'Hiked 3 trails at Living Desert Zoo and Gardens State Park', 'NM'),
('manzano_mountains_state_park_state_park', 'Manzano Mountains State Park', 'Hiked 3 trails at Manzano Mountains State Park', 'NM'),
('mesilla_valley_bosque_state_park_state_park', 'Mesilla Valley Bosque State Park', 'Hiked 3 trails at Mesilla Valley Bosque State Park', 'NM'),
('morphy_lake_state_park_state_park', 'Morphy Lake State Park', 'Hiked 3 trails at Morphy Lake State Park', 'NM'),
('navajo_lake_state_park_state_park', 'Navajo Lake State Park', 'Hiked 3 trails at Navajo Lake State Park', 'NM'),
('oasis_state_park_state_park', 'Oasis State Park', 'Hiked 3 trails at Oasis State Park', 'NM'),
('oliver_lee_memorial_state_park_state_park', 'Oliver Lee Memorial State Park', 'Hiked 3 trails at Oliver Lee Memorial State Park', 'NM'),
('pancho_villa_state_park_state_park', 'Pancho Villa State Park', 'Hiked 3 trails at Pancho Villa State Park', 'NM'),
('pecos_canyon_state_park_state_park', 'Pecos Canyon State Park', 'Hiked 3 trails at Pecos Canyon State Park', 'NM'),
('percha_dam_state_park_state_park', 'Percha Dam State Park', 'Hiked 3 trails at Percha Dam State Park', 'NM'),
('rio_grande_nature_center_state_park_state_park', 'Rio Grande Nature Center State Park', 'Hiked 3 trails at Rio Grande Nature Center State Park', 'NM'),
('rockhound_state_park_state_park', 'Rockhound State Park', 'Hiked 3 trails at Rockhound State Park', 'NM'),
('santa_rosa_lake_state_park_state_park', 'Santa Rosa Lake State Park', 'Hiked 3 trails at Santa Rosa Lake State Park', 'NM'),
('storrie_lake_state_park_state_park', 'Storrie Lake State Park', 'Hiked 3 trails at Storrie Lake State Park', 'NM'),
('sugarite_canyon_state_park_state_park', 'Sugarite Canyon State Park', 'Hiked 3 trails at Sugarite Canyon State Park', 'NM'),
('sumner_lake_state_park_state_park', 'Sumner Lake State Park', 'Hiked 3 trails at Sumner Lake State Park', 'NM'),
('ute_lake_state_park_state_park', 'Ute Lake State Park', 'Hiked 3 trails at Ute Lake State Park', 'NM'),
('villanueva_state_park_state_park', 'Villanueva State Park', 'Hiked 3 trails at Villanueva State Park', 'NM'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('genesee_state_park', 'Genesee', 'Hiked 3 trails at Genesee', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('allegany_state_park', 'Allegany', 'Hiked 3 trails at Allegany', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('palisades_state_park', 'Palisades', 'Hiked 3 trails at Palisades', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('thousand_islands_state_park', 'Thousand Islands', 'Hiked 3 trails at Thousand Islands', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('long_island_state_park', 'Long Island', 'Hiked 3 trails at Long Island', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('taconic_state_park', 'Taconic', 'Hiked 3 trails at Taconic', 'NY'),
('niagara_state_park', 'Niagara', 'Hiked 3 trails at Niagara', 'NY'),
('new_york_city_state_park', 'New York City', 'Hiked 3 trails at New York City', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('central_state_park', 'Central', 'Hiked 3 trails at Central', 'NY'),
('saratogacapital_district_state_park', 'Saratoga/Capital District', 'Hiked 3 trails at Saratoga/Capital District', 'NY'),
('finger_lakes_state_park', 'Finger Lakes', 'Hiked 3 trails at Finger Lakes', 'NY'),
('goose_lake_state_recreation_area_state_park', 'Goose Lake State Recreation Area', 'Hiked 3 trails at Goose Lake State Recreation Area', 'OR'),
('frenchglen_hotel_state_heritage_site_state_park', 'Frenchglen Hotel State Heritage Site', 'Hiked 3 trails at Frenchglen Hotel State Heritage Site', 'OR'),
('ontario_state_recreation_site_state_park', 'Ontario State Recreation Site', 'Hiked 3 trails at Ontario State Recreation Site', 'OR'),
('farewell_bend_state_recreation_area_state_park', 'Farewell Bend State Recreation Area', 'Hiked 3 trails at Farewell Bend State Recreation Area', 'OR'),
('kam_wah_chung_state_heritage_site_state_park', 'Kam Wah Chung State Heritage Site', 'Hiked 3 trails at Kam Wah Chung State Heritage Site', 'OR'),
('unity_forest_state_scenic_corridor_state_park', 'Unity Forest State Scenic Corridor', 'Hiked 3 trails at Unity Forest State Scenic Corridor', 'OR'),
('unity_lake_state_recreation_site_state_park', 'Unity Lake State Recreation Site', 'Hiked 3 trails at Unity Lake State Recreation Site', 'OR'),
('clyde_holliday_state_recreation_site_state_park', 'Clyde Holliday State Recreation Site', 'Hiked 3 trails at Clyde Holliday State Recreation Site', 'OR'),
('succor_creek_state_natural_area_state_park', 'Succor Creek State Natural Area', 'Hiked 3 trails at Succor Creek State Natural Area', 'OR'),
('lake_owyhee_state_park_state_park', 'Lake Owyhee State Park', 'Hiked 3 trails at Lake Owyhee State Park', 'OR'),
('catherine_creek_state_park_state_park', 'Catherine Creek State Park', 'Hiked 3 trails at Catherine Creek State Park', 'OR'),
('hat_rock_state_park_state_park', 'Hat Rock State Park', 'Hiked 3 trails at Hat Rock State Park', 'OR'),
('hilgard_junction_state_recreation_area_state_park', 'Hilgard Junction State Recreation Area', 'Hiked 3 trails at Hilgard Junction State Recreation Area', 'OR'),
('red_bridge_state_wayside_state_park', 'Red Bridge State Wayside', 'Hiked 3 trails at Red Bridge State Wayside', 'OR'),
('ukiahdale_forest_state_scenic_corridor_state_park', 'Ukiah–Dale Forest State Scenic Corridor', 'Hiked 3 trails at Ukiah–Dale Forest State Scenic Corridor', 'OR'),
('emigrant_springs_state_heritage_area_state_park', 'Emigrant Springs State Heritage Area', 'Hiked 3 trails at Emigrant Springs State Heritage Area', 'OR'),
('wallowa_lake_highway_forest_state_scenic_corridor_state_park', 'Wallowa Lake Highway Forest State Scenic Corridor', 'Hiked 3 trails at Wallowa Lake Highway Forest State Scenic Corridor', 'OR'),
('wallowa_river_rest_area_state_park', 'Wallowa River Rest Area', 'Hiked 3 trails at Wallowa River Rest Area', 'OR'),
('minam_state_recreation_area_state_park', 'Minam State Recreation Area', 'Hiked 3 trails at Minam State Recreation Area', 'OR'),
('wallowa_lake_state_recreation_area_state_park', 'Wallowa Lake State Recreation Area', 'Hiked 3 trails at Wallowa Lake State Recreation Area', 'OR'),
('iwetemlaykin_state_heritage_site_state_park', 'Iwetemlaykin State Heritage Site', 'Hiked 3 trails at Iwetemlaykin State Heritage Site', 'OR'),
('casey_state_recreation_site_state_park', 'Casey State Recreation Site', 'Hiked 3 trails at Casey State Recreation Site', 'OR'),
('prospect_state_scenic_viewpoint_state_park', 'Prospect State Scenic Viewpoint', 'Hiked 3 trails at Prospect State Scenic Viewpoint', 'OR'),
('joseph_h_stewart_state_recreation_area_state_park', 'Joseph H. Stewart State Recreation Area', 'Hiked 3 trails at Joseph H. Stewart State Recreation Area', 'OR'),
('the_cove_palisades_state_park_state_park', 'The Cove Palisades State Park', 'Hiked 3 trails at The Cove Palisades State Park', 'OR'),
('jasper_point_campground_state_park', 'Jasper Point Campground', 'Hiked 3 trails at Jasper Point Campground', 'OR'),
('prineville_reservoir_state_park_state_park', 'Prineville Reservoir State Park', 'Hiked 3 trails at Prineville Reservoir State Park', 'OR'),
('heritage_landing_deschutes_state_park', 'Heritage Landing (Deschutes)', 'Hiked 3 trails at Heritage Landing (Deschutes)', 'OR'),
('white_river_falls_state_park_state_park', 'White River Falls State Park', 'Hiked 3 trails at White River Falls State Park', 'OR'),
('deschutes_river_state_recreation_area_state_park', 'Deschutes River State Recreation Area', 'Hiked 3 trails at Deschutes River State Recreation Area', 'OR'),
('cline_falls_state_scenic_viewpoint_state_park', 'Cline Falls State Scenic Viewpoint', 'Hiked 3 trails at Cline Falls State Scenic Viewpoint', 'OR'),
('fort_rock_state_natural_area_state_park', 'Fort Rock State Natural Area', 'Hiked 3 trails at Fort Rock State Natural Area', 'OR'),
('la_pine_state_park_state_park', 'La Pine State Park', 'Hiked 3 trails at La Pine State Park', 'OR'),
('pilot_butte_state_scenic_viewpoint_state_park', 'Pilot Butte State Scenic Viewpoint', 'Hiked 3 trails at Pilot Butte State Scenic Viewpoint', 'OR'),
('tumalo_state_park_state_park', 'Tumalo State Park', 'Hiked 3 trails at Tumalo State Park', 'OR'),
('peter_skene_ogden_state_scenic_viewpoint_state_park', 'Peter Skene Ogden State Scenic Viewpoint', 'Hiked 3 trails at Peter Skene Ogden State Scenic Viewpoint', 'OR'),
('smith_rock_state_park_state_park', 'Smith Rock State Park', 'Hiked 3 trails at Smith Rock State Park', 'OR'),
('booth_state_scenic_corridor_state_park', 'Booth State Scenic Corridor', 'Hiked 3 trails at Booth State Scenic Corridor', 'OR'),
('chandler_state_wayside_state_park', 'Chandler State Wayside', 'Hiked 3 trails at Chandler State Wayside', 'OR'),
('geisel_monument_state_heritage_site_state_park', 'Geisel Monument State Heritage Site', 'Hiked 3 trails at Geisel Monument State Heritage Site', 'OR'),
('humbug_mountain_state_park_state_park', 'Humbug Mountain State Park', 'Hiked 3 trails at Humbug Mountain State Park', 'OR'),
('otter_point_state_recreation_site_state_park', 'Otter Point State Recreation Site', 'Hiked 3 trails at Otter Point State Recreation Site', 'OR'),
('paradise_point_state_recreation_site_state_park', 'Paradise Point State Recreation Site', 'Hiked 3 trails at Paradise Point State Recreation Site', 'OR'),
('port_orford_heads_state_park_state_park', 'Port Orford Heads State Park', 'Hiked 3 trails at Port Orford Heads State Park', 'OR'),
('cape_blanco_state_park_state_park', 'Cape Blanco State Park', 'Hiked 3 trails at Cape Blanco State Park', 'OR'),
('bandon_state_natural_area_state_park', 'Bandon State Natural Area', 'Hiked 3 trails at Bandon State Natural Area', 'OR'),
('coquille_myrtle_grove_state_natural_site_state_park', 'Coquille Myrtle Grove State Natural Site', 'Hiked 3 trails at Coquille Myrtle Grove State Natural Site', 'OR'),
('face_rock_state_scenic_viewpoint_state_park', 'Face Rock State Scenic Viewpoint', 'Hiked 3 trails at Face Rock State Scenic Viewpoint', 'OR'),
('hoffman_memorial_state_wayside_state_park', 'Hoffman Memorial State Wayside', 'Hiked 3 trails at Hoffman Memorial State Wayside', 'OR'),
('seven_devils_state_recreation_site_state_park', 'Seven Devils State Recreation Site', 'Hiked 3 trails at Seven Devils State Recreation Site', 'OR'),
('bullards_beach_state_park_state_park', 'Bullards Beach State Park', 'Hiked 3 trails at Bullards Beach State Park', 'OR'),
('alfred_a_loeb_state_park_state_park', 'Alfred A. Loeb State Park', 'Hiked 3 trails at Alfred A. Loeb State Park', 'OR'),
('cape_sebastian_state_scenic_corridor_state_park', 'Cape Sebastian State Scenic Corridor', 'Hiked 3 trails at Cape Sebastian State Scenic Corridor', 'OR'),
('crissey_field_state_recreation_site_state_park', 'Crissey Field State Recreation Site', 'Hiked 3 trails at Crissey Field State Recreation Site', 'OR'),
('mcvay_rock_state_recreation_site_state_park', 'McVay Rock State Recreation Site', 'Hiked 3 trails at McVay Rock State Recreation Site', 'OR'),
('pistol_river_state_scenic_viewpoint_state_park', 'Pistol River State Scenic Viewpoint', 'Hiked 3 trails at Pistol River State Scenic Viewpoint', 'OR'),
('samuel_h_boardman_state_scenic_corridor_state_park', 'Samuel H. Boardman State Scenic Corridor', 'Hiked 3 trails at Samuel H. Boardman State Scenic Corridor', 'OR'),
('winchuck_state_recreation_site_state_park', 'Winchuck State Recreation Site', 'Hiked 3 trails at Winchuck State Recreation Site', 'OR'),
('harris_beach_state_recreation_area_state_park', 'Harris Beach State Recreation Area', 'Hiked 3 trails at Harris Beach State Recreation Area', 'OR'),
('alderwood_state_wayside_state_park', 'Alderwood State Wayside', 'Hiked 3 trails at Alderwood State Wayside', 'OR'),
('elijah_bristow_state_park_state_park', 'Elijah Bristow State Park', 'Hiked 3 trails at Elijah Bristow State Park', 'OR'),
('washburne_state_wayside_state_park', 'Washburne State Wayside', 'Hiked 3 trails at Washburne State Wayside', 'OR'),
('mongold_dayuse_area_state_park', 'Mongold Day-Use Area', 'Hiked 3 trails at Mongold Day-Use Area', 'OR'),
('north_santiam_state_recreation_area_state_park', 'North Santiam State Recreation Area', 'Hiked 3 trails at North Santiam State Recreation Area', 'OR'),
('detroit_lake_state_recreation_area_state_park', 'Detroit Lake State Recreation Area', 'Hiked 3 trails at Detroit Lake State Recreation Area', 'OR'),
('cape_arago_state_park_state_park', 'Cape Arago State Park', 'Hiked 3 trails at Cape Arago State Park', 'OR'),
('golden_and_silver_falls_state_natural_area_state_park', 'Golden and Silver Falls State Natural Area', 'Hiked 3 trails at Golden and Silver Falls State Natural Area', 'OR'),
('shore_acres_state_park_state_park', 'Shore Acres State Park', 'Hiked 3 trails at Shore Acres State Park', 'OR'),
('william_m_tugman_state_park_state_park', 'William M. Tugman State Park', 'Hiked 3 trails at William M. Tugman State Park', 'OR'),
('sunset_bay_state_park_state_park', 'Sunset Bay State Park', 'Hiked 3 trails at Sunset Bay State Park', 'OR'),
('illinois_river_forks_state_park_state_park', 'Illinois River Forks State Park', 'Hiked 3 trails at Illinois River Forks State Park', 'OR'),
('touvelle_state_recreation_site_state_park', 'TouVelle State Recreation Site', 'Hiked 3 trails at TouVelle State Recreation Site', 'OR'),
('tub_springs_state_wayside_state_park', 'Tub Springs State Wayside', 'Hiked 3 trails at Tub Springs State Wayside', 'OR'),
('wolf_creek_inn_state_heritage_site_state_park', 'Wolf Creek Inn State Heritage Site', 'Hiked 3 trails at Wolf Creek Inn State Heritage Site', 'OR'),
('valley_of_the_rogue_state_recreation_area_state_park', 'Valley of the Rogue State Recreation Area', 'Hiked 3 trails at Valley of the Rogue State Recreation Area', 'OR'),
('bald_peak_state_scenic_viewpoint_state_park', 'Bald Peak State Scenic Viewpoint', 'Hiked 3 trails at Bald Peak State Scenic Viewpoint', 'OR'),
('molalla_river_state_park_state_park', 'Molalla River State Park', 'Hiked 3 trails at Molalla River State Park', 'OR'),
('champoeg_state_heritage_area_state_park', 'Champoeg State Heritage Area', 'Hiked 3 trails at Champoeg State Heritage Area', 'OR'),
('beaver_creek_state_natural_area_state_park', 'Beaver Creek State Natural Area', 'Hiked 3 trails at Beaver Creek State Natural Area', 'OR'),
('bolon_island_tideways_state_scenic_corridor_state_park', 'Bolon Island Tideways State Scenic Corridor', 'Hiked 3 trails at Bolon Island Tideways State Scenic Corridor', 'OR'),
('darlingtonia_state_natural_site_state_park', 'Darlingtonia State Natural Site', 'Hiked 3 trails at Darlingtonia State Natural Site', 'OR'),
('governor_patterson_memorial_state_recreation_site_state_park', 'Governor Patterson Memorial State Recreation Site', 'Hiked 3 trails at Governor Patterson Memorial State Recreation Site', 'OR'),
('umpqua_lighthouse_state_park_state_park', 'Umpqua Lighthouse State Park', 'Hiked 3 trails at Umpqua Lighthouse State Park', 'OR'),
('beachside_state_recreation_site_state_park', 'Beachside State Recreation Site', 'Hiked 3 trails at Beachside State Recreation Site', 'OR'),
('carl_g_washburne_memorial_state_park_state_park', 'Carl G. Washburne Memorial State Park', 'Hiked 3 trails at Carl G. Washburne Memorial State Park', 'OR'),
('heceta_head_lighthouse_state_scenic_viewpoint_state_park', 'Heceta Head Lighthouse State Scenic Viewpoint', 'Hiked 3 trails at Heceta Head Lighthouse State Scenic Viewpoint', 'OR'),
('muriel_o_ponsler_memorial_state_scenic_viewpoint_state_park', 'Muriel O. Ponsler Memorial State Scenic Viewpoint', 'Hiked 3 trails at Muriel O. Ponsler Memorial State Scenic Viewpoint', 'OR'),
('neptune_state_scenic_viewpoint_state_park', 'Neptune State Scenic Viewpoint', 'Hiked 3 trails at Neptune State Scenic Viewpoint', 'OR'),
('smelt_sands_state_recreation_site_state_park', 'Smelt Sands State Recreation Site', 'Hiked 3 trails at Smelt Sands State Recreation Site', 'OR'),
('tokatee_klootchman_state_natural_site_state_park', 'Tokatee Klootchman State Natural Site', 'Hiked 3 trails at Tokatee Klootchman State Natural Site', 'OR'),
('stonefield_beach_state_recreation_site_state_park', 'Stonefield Beach State Recreation Site', 'Hiked 3 trails at Stonefield Beach State Recreation Site', 'OR'),
('w_b_nelson_state_recreation_site_state_park', 'W. B. Nelson State Recreation Site', 'Hiked 3 trails at W. B. Nelson State Recreation Site', 'OR'),
('yachats_ocean_road_state_natural_site_state_park', 'Yachats Ocean Road State Natural Site', 'Hiked 3 trails at Yachats Ocean Road State Natural Site', 'OR'),
('yachats_state_recreation_area_state_park', 'Yachats State Recreation Area', 'Hiked 3 trails at Yachats State Recreation Area', 'OR'),
('jessie_m_honeyman_memorial_state_park_state_park', 'Jessie M. Honeyman Memorial State Park', 'Hiked 3 trails at Jessie M. Honeyman Memorial State Park', 'OR'),
('erratic_rock_state_natural_site_state_park', 'Erratic Rock State Natural Site', 'Hiked 3 trails at Erratic Rock State Natural Site', 'OR'),
('holman_state_wayside_state_park', 'Holman State Wayside', 'Hiked 3 trails at Holman State Wayside', 'OR'),
('maud_williamson_state_recreation_site_state_park', 'Maud Williamson State Recreation Site', 'Hiked 3 trails at Maud Williamson State Recreation Site', 'OR'),
('sarah_helmick_state_recreation_site_state_park', 'Sarah Helmick State Recreation Site', 'Hiked 3 trails at Sarah Helmick State Recreation Site', 'OR'),
('willamette_mission_state_park_state_park', 'Willamette Mission State Park', 'Hiked 3 trails at Willamette Mission State Park', 'OR'),
('bonnie_lure_state_recreation_area_state_park', 'Bonnie Lure State Recreation Area', 'Hiked 3 trails at Bonnie Lure State Recreation Area', 'OR'),
('mary_s_young_state_recreation_area_state_park', 'Mary S. Young State Recreation Area', 'Hiked 3 trails at Mary S. Young State Recreation Area', 'OR'),
('milo_mciver_state_park_state_park', 'Milo McIver State Park', 'Hiked 3 trails at Milo McIver State Park', 'OR'),
('tryon_creek_state_natural_area_state_park', 'Tryon Creek State Natural Area', 'Hiked 3 trails at Tryon Creek State Natural Area', 'OR'),
('banksvernonia_state_trail_state_park', 'Banks–Vernonia State Trail', 'Hiked 3 trails at Banks–Vernonia State Trail', 'OR'),
('ainsworth_state_park_state_park', 'Ainsworth State Park', 'Hiked 3 trails at Ainsworth State Park', 'OR'),
('benson_state_recreation_area_state_park', 'Benson State Recreation Area', 'Hiked 3 trails at Benson State Recreation Area', 'OR'),
('bridal_veil_falls_state_scenic_viewpoint_state_park', 'Bridal Veil Falls State Scenic Viewpoint', 'Hiked 3 trails at Bridal Veil Falls State Scenic Viewpoint', 'OR'),
('crown_point_state_scenic_corridor_state_park', 'Crown Point State Scenic Corridor', 'Hiked 3 trails at Crown Point State Scenic Corridor', 'OR'),
('dabney_state_recreation_area_state_park', 'Dabney State Recreation Area', 'Hiked 3 trails at Dabney State Recreation Area', 'OR'),
('george_w_joseph_state_natural_area_accessible_from_guy_w_talbot_state_park_state_park', 'George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)', 'Hiked 3 trails at George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)', 'OR'),
('guy_w_talbot_state_park_state_park', 'Guy W. Talbot State Park', 'Hiked 3 trails at Guy W. Talbot State Park', 'OR'),
('historic_columbia_river_highway_state_trail_state_park', 'Historic Columbia River Highway State Trail', 'Hiked 3 trails at Historic Columbia River Highway State Trail', 'OR'),
('john_b_yeon_state_scenic_corridor_state_park', 'John B. Yeon State Scenic Corridor', 'Hiked 3 trails at John B. Yeon State Scenic Corridor', 'OR'),
('koberg_beach_state_recreation_site_state_park', 'Koberg Beach State Recreation Site', 'Hiked 3 trails at Koberg Beach State Recreation Site', 'OR'),
('lewis_and_clark_state_recreation_site_state_park', 'Lewis and Clark State Recreation Site', 'Hiked 3 trails at Lewis and Clark State Recreation Site', 'OR'),
('mayer_state_park_state_park', 'Mayer State Park', 'Hiked 3 trails at Mayer State Park', 'OR'),
('memaloose_state_park_state_park', 'Memaloose State Park', 'Hiked 3 trails at Memaloose State Park', 'OR'),
('portland_womens_forum_state_scenic_viewpoint_state_park', 'Portland Women''s Forum State Scenic Viewpoint', 'Hiked 3 trails at Portland Women''s Forum State Scenic Viewpoint', 'OR'),
('seneca_fouts_memorial_state_natural_area_state_park', 'Seneca Fouts Memorial State Natural Area', 'Hiked 3 trails at Seneca Fouts Memorial State Natural Area', 'OR'),
('shepperds_dell_state_natural_area_state_park', 'Shepperd''s Dell State Natural Area', 'Hiked 3 trails at Shepperd''s Dell State Natural Area', 'OR'),
('sheridan_state_scenic_corridor_state_park', 'Sheridan State Scenic Corridor', 'Hiked 3 trails at Sheridan State Scenic Corridor', 'OR'),
('starvation_creek_state_park_state_park', 'Starvation Creek State Park', 'Hiked 3 trails at Starvation Creek State Park', 'OR'),
('viento_state_park_state_park', 'Viento State Park', 'Hiked 3 trails at Viento State Park', 'OR'),
('vinzenz_lausmann_memorial_state_natural_area_state_park', 'Vinzenz Lausmann Memorial State Natural Area', 'Hiked 3 trails at Vinzenz Lausmann Memorial State Natural Area', 'OR'),
('wygant_state_natural_area_state_park', 'Wygant State Natural Area', 'Hiked 3 trails at Wygant State Natural Area', 'OR'),
('rooster_rock_state_park_state_park', 'Rooster Rock State Park', 'Hiked 3 trails at Rooster Rock State Park', 'OR'),
('bradley_state_scenic_viewpoint_state_park', 'Bradley State Scenic Viewpoint', 'Hiked 3 trails at Bradley State Scenic Viewpoint', 'OR'),
('del_rey_beach_state_recreation_site_state_park', 'Del Rey Beach State Recreation Site', 'Hiked 3 trails at Del Rey Beach State Recreation Site', 'OR'),
('fort_stevens_state_park_state_park', 'Fort Stevens State Park', 'Hiked 3 trails at Fort Stevens State Park', 'OR'),
('cape_kiwanda_state_natural_area_state_park', 'Cape Kiwanda State Natural Area', 'Hiked 3 trails at Cape Kiwanda State Natural Area', 'OR'),
('cape_meares_state_scenic_viewpoint_state_park', 'Cape Meares State Scenic Viewpoint', 'Hiked 3 trails at Cape Meares State Scenic Viewpoint', 'OR'),
('oceanside_beach_state_recreation_site_state_park', 'Oceanside Beach State Recreation Site', 'Hiked 3 trails at Oceanside Beach State Recreation Site', 'OR'),
('bob_straub_state_park_state_park', 'Bob Straub State Park', 'Hiked 3 trails at Bob Straub State Park', 'OR'),
('cape_lookout_state_park_state_park', 'Cape Lookout State Park', 'Hiked 3 trails at Cape Lookout State Park', 'OR'),
('arcadia_beach_state_recreation_site_state_park', 'Arcadia Beach State Recreation Site', 'Hiked 3 trails at Arcadia Beach State Recreation Site', 'OR'),
('ecola_state_park_state_park', 'Ecola State Park', 'Hiked 3 trails at Ecola State Park', 'OR'),
('golden_state_heritage_site_state_park', 'Golden State Heritage Site', 'Hiked 3 trails at Golden State Heritage Site', 'OR'),
('hug_point_state_recreation_site_state_park', 'Hug Point State Recreation Site', 'Hiked 3 trails at Hug Point State Recreation Site', 'OR'),
('manhattan_beach_state_recreation_site_state_park', 'Manhattan Beach State Recreation Site', 'Hiked 3 trails at Manhattan Beach State Recreation Site', 'OR'),
('oswald_west_state_park_state_park', 'Oswald West State Park', 'Hiked 3 trails at Oswald West State Park', 'OR'),
('saddle_mountain_state_natural_area_state_park', 'Saddle Mountain State Natural Area', 'Hiked 3 trails at Saddle Mountain State Natural Area', 'OR'),
('tolovana_beach_state_recreation_site_state_park', 'Tolovana Beach State Recreation Site', 'Hiked 3 trails at Tolovana Beach State Recreation Site', 'OR'),
('nehalem_bay_state_park_state_park', 'Nehalem Bay State Park', 'Hiked 3 trails at Nehalem Bay State Park', 'OR'),
('alsea_bay_historic_interpretive_center_state_park', 'Alsea Bay Historic Interpretive Center', 'Hiked 3 trails at Alsea Bay Historic Interpretive Center', 'OR'),
('driftwood_beach_state_recreation_site_state_park', 'Driftwood Beach State Recreation Site', 'Hiked 3 trails at Driftwood Beach State Recreation Site', 'OR'),
('lost_creek_state_recreation_site_state_park', 'Lost Creek State Recreation Site', 'Hiked 3 trails at Lost Creek State Recreation Site', 'OR'),
('ona_beach_state_park_state_park', 'Ona Beach State Park', 'Hiked 3 trails at Ona Beach State Park', 'OR'),
('seal_rock_state_recreation_site_state_park', 'Seal Rock State Recreation Site', 'Hiked 3 trails at Seal Rock State Recreation Site', 'OR'),
('yaquina_bay_state_recreation_site_state_park', 'Yaquina Bay State Recreation Site', 'Hiked 3 trails at Yaquina Bay State Recreation Site', 'OR'),
('south_beach_state_park_state_park', 'South Beach State Park', 'Hiked 3 trails at South Beach State Park', 'OR'),
('silver_falls_state_park_state_park', 'Silver Falls State Park', 'Hiked 3 trails at Silver Falls State Park', 'OR'),
('agate_beach_state_recreation_site_state_park', 'Agate Beach State Recreation Site', 'Hiked 3 trails at Agate Beach State Recreation Site', 'OR'),
('boiler_bay_state_scenic_viewpoint_state_park', 'Boiler Bay State Scenic Viewpoint', 'Hiked 3 trails at Boiler Bay State Scenic Viewpoint', 'OR'),
('d_river_state_recreation_site_state_park', 'D River State Recreation Site', 'Hiked 3 trails at D River State Recreation Site', 'OR'),
('devils_lake_state_recreation_area_state_park', 'Devils Lake State Recreation Area', 'Hiked 3 trails at Devils Lake State Recreation Area', 'OR'),
('devils_punch_bowl_state_natural_area_state_park', 'Devils Punch Bowl State Natural Area', 'Hiked 3 trails at Devils Punch Bowl State Natural Area', 'OR'),
('ellmaker_state_wayside_state_park', 'Ellmaker State Wayside', 'Hiked 3 trails at Ellmaker State Wayside', 'OR'),
('fogarty_creek_state_recreation_area_state_park', 'Fogarty Creek State Recreation Area', 'Hiked 3 trails at Fogarty Creek State Recreation Area', 'OR'),
('gleneden_beach_state_recreation_site_state_park', 'Gleneden Beach State Recreation Site', 'Hiked 3 trails at Gleneden Beach State Recreation Site', 'OR'),
('h_b_van_duzer_forest_state_scenic_corridor_state_park', 'H. B. Van Duzer Forest State Scenic Corridor', 'Hiked 3 trails at H. B. Van Duzer Forest State Scenic Corridor', 'OR'),
('neskowin_beach_state_recreation_site_state_park', 'Neskowin Beach State Recreation Site', 'Hiked 3 trails at Neskowin Beach State Recreation Site', 'OR'),
('otter_crest_state_scenic_viewpoint_state_park', 'Otter Crest State Scenic Viewpoint', 'Hiked 3 trails at Otter Crest State Scenic Viewpoint', 'OR'),
('roads_end_state_recreation_site_state_park', 'Roads End State Recreation Site', 'Hiked 3 trails at Roads End State Recreation Site', 'OR'),
('beverly_beach_state_park_state_park', 'Beverly Beach State Park', 'Hiked 3 trails at Beverly Beach State Park', 'OR'),
('collier_memorial_state_park_state_park', 'Collier Memorial State Park', 'Hiked 3 trails at Collier Memorial State Park', 'OR'),
('jackson_f_kimball_state_recreation_site_state_park', 'Jackson F. Kimball State Recreation Site', 'Hiked 3 trails at Jackson F. Kimball State Recreation Site', 'OR'),
('oce_woods_line_state_trail_state_park', 'OC&E Woods Line State Trail', 'Hiked 3 trails at OC&E Woods Line State Trail', 'OR'),
('south_jetty_south_beach_state_park', 'South Jetty (South Beach)', 'Hiked 3 trails at South Jetty (South Beach)', 'OR'),
('blue_mountain_forest_state_scenic_corridor_state_park', 'Blue Mountain Forest State Scenic Corridor', 'Hiked 3 trails at Blue Mountain Forest State Scenic Corridor', 'OR'),
('battle_mountain_forest_state_scenic_corridor_state_park', 'Battle Mountain Forest State Scenic Corridor', 'Hiked 3 trails at Battle Mountain Forest State Scenic Corridor', 'OR'),
('sumpter_valley_dredge_state_heritage_area_state_park', 'Sumpter Valley Dredge State Heritage Area', 'Hiked 3 trails at Sumpter Valley Dredge State Heritage Area', 'OR'),
('fall_creek_state_recreation_site_state_park', 'Fall Creek State Recreation Site', 'Hiked 3 trails at Fall Creek State Recreation Site', 'OR'),
('lowell_state_recreation_site_state_park', 'Lowell State Recreation Site', 'Hiked 3 trails at Lowell State Recreation Site', 'OR'),
('jasper_state_recreation_site_state_park', 'Jasper State Recreation Site', 'Hiked 3 trails at Jasper State Recreation Site', 'OR'),
('dexter_state_recreation_site_state_park', 'Dexter State Recreation Site', 'Hiked 3 trails at Dexter State Recreation Site', 'OR'),
('munson_creek_falls_state_natural_site_state_park', 'Munson Creek Falls State Natural Site', 'Hiked 3 trails at Munson Creek Falls State Natural Site', 'OR'),
('willamette_stone_state_heritage_site_state_park', 'Willamette Stone State Heritage Site', 'Hiked 3 trails at Willamette Stone State Heritage Site', 'OR'),
('umpqua_state_scenic_corridor_state_park', 'Umpqua State Scenic Corridor', 'Hiked 3 trails at Umpqua State Scenic Corridor', 'OR'),
('clay_myers_state_natural_area_at_whalen_island_state_park', 'Clay Myers State Natural Area at Whalen Island', 'Hiked 3 trails at Clay Myers State Natural Area at Whalen Island', 'OR'),
('fort_rock_cave_near_fort_rock_state_natural_area_state_park', 'Fort Rock Cave (near Fort Rock State Natural Area)', 'Hiked 3 trails at Fort Rock Cave (near Fort Rock State Natural Area)', 'OR'),
('government_island_state_recreation_area_state_park', 'Government Island State Recreation Area', 'Hiked 3 trails at Government Island State Recreation Area', 'OR'),
('sunset_beach_state_recreation_site_state_park', 'Sunset Beach State Recreation Site', 'Hiked 3 trails at Sunset Beach State Recreation Site', 'OR'),
('whale_watching_center_state_park', 'Whale Watching Center', 'Hiked 3 trails at Whale Watching Center', 'OR'),
('rocky_creek_state_scenic_viewpoint_state_park', 'Rocky Creek State Scenic Viewpoint', 'Hiked 3 trails at Rocky Creek State Scenic Viewpoint', 'OR'),
('fort_yamhill_state_heritage_area_state_park', 'Fort Yamhill State Heritage Area', 'Hiked 3 trails at Fort Yamhill State Heritage Area', 'OR'),
('l_l_stub_stewart_state_park_state_park', 'L. L. "Stub" Stewart State Park', 'Hiked 3 trails at L. L. "Stub" Stewart State Park', 'OR'),
('thompsons_mills_state_heritage_site_state_park', 'Thompson''s Mills State Heritage Site', 'Hiked 3 trails at Thompson''s Mills State Heritage Site', 'OR'),
('state_capitol_state_park_state_park', 'State Capitol State Park', 'Hiked 3 trails at State Capitol State Park', 'OR'),
('arizona_beach_state_recreation_site_state_park', 'Arizona Beach State Recreation Site', 'Hiked 3 trails at Arizona Beach State Recreation Site', 'OR'),
('bates_state_park_state_park', 'Bates State Park', 'Hiked 3 trails at Bates State Park', 'OR'),
('ochoco_state_scenic_viewpoint_state_park', 'Ochoco State Scenic Viewpoint', 'Hiked 3 trails at Ochoco State Scenic Viewpoint', 'OR'),
('dyer_state_wayside_state_park', 'Dyer State Wayside', 'Hiked 3 trails at Dyer State Wayside', 'OR'),
('pete_french_round_barn_state_heritage_site_state_park', 'Pete French Round Barn State Heritage Site', 'Hiked 3 trails at Pete French Round Barn State Heritage Site', 'OR'),
('warm_springs_state_recreation_site_state_park', 'Warm Springs State Recreation Site', 'Hiked 3 trails at Warm Springs State Recreation Site', 'OR'),
('cottonwood_canyon_state_park_state_park', 'Cottonwood Canyon State Park', 'Hiked 3 trails at Cottonwood Canyon State Park', 'OR'),
('sitka_sedge_state_natural_area_state_park', 'Sitka Sedge State Natural Area', 'Hiked 3 trails at Sitka Sedge State Natural Area', 'OR'),
('tseriadun_state_recreation_site_state_park', 'Tseriadun State Recreation Site', 'Hiked 3 trails at Tseriadun State Recreation Site', 'OR'),
('abilene_state_park_state_park', 'Abilene State Park', 'Hiked 3 trails at Abilene State Park', 'TX'),
('atlanta_state_park_state_park', 'Atlanta State Park', 'Hiked 3 trails at Atlanta State Park', 'TX'),
('balmorhea_state_park_state_park', 'Balmorhea State Park', 'Hiked 3 trails at Balmorhea State Park', 'TX'),
('barton_warnock_visitor_center_state_park', 'Barton Warnock Visitor Center', 'Hiked 3 trails at Barton Warnock Visitor Center', 'TX'),
('bastrop_state_park_state_park', 'Bastrop State Park', 'Hiked 3 trails at Bastrop State Park', 'TX'),
('bentsenrio_grande_valley_state_park_state_park', 'Bentsen-Rio Grande Valley State Park', 'Hiked 3 trails at Bentsen-Rio Grande Valley State Park', 'TX'),
('big_bend_ranch_state_park_state_park', 'Big Bend Ranch State Park', 'Hiked 3 trails at Big Bend Ranch State Park', 'TX'),
('big_spring_state_park_state_park', 'Big Spring State Park', 'Hiked 3 trails at Big Spring State Park', 'TX'),
('blanco_state_park_state_park', 'Blanco State Park', 'Hiked 3 trails at Blanco State Park', 'TX'),
('bonham_state_park_state_park', 'Bonham State Park', 'Hiked 3 trails at Bonham State Park', 'TX'),
('brazos_bend_state_park_state_park', 'Brazos Bend State Park', 'Hiked 3 trails at Brazos Bend State Park', 'TX'),
('buescher_state_park_state_park', 'Buescher State Park', 'Hiked 3 trails at Buescher State Park', 'TX'),
('caddo_lake_state_park_state_park', 'Caddo Lake State Park', 'Hiked 3 trails at Caddo Lake State Park', 'TX'),
('caprock_canyons_state_park_and_trailway_state_park', 'Caprock Canyons State Park and Trailway', 'Hiked 3 trails at Caprock Canyons State Park and Trailway', 'TX'),
('cedar_hill_state_park__includes_penn_farm_agricultural_history_center_state_park', 'Cedar Hill State Park - includes Penn Farm Agricultural History Center', 'Hiked 3 trails at Cedar Hill State Park - includes Penn Farm Agricultural History Center', 'TX'),
('choke_canyon_state_park__includes_calliham_unit_and_south_shore_unit_state_park', 'Choke Canyon State Park - includes Calliham Unit and South Shore Unit', 'Hiked 3 trails at Choke Canyon State Park - includes Calliham Unit and South Shore Unit', 'TX'),
('cleburne_state_park_state_park', 'Cleburne State Park', 'Hiked 3 trails at Cleburne State Park', 'TX'),
('colorado_bend_state_park_state_park', 'Colorado Bend State Park', 'Hiked 3 trails at Colorado Bend State Park', 'TX'),
('cooper_lake_state_park__includes_doctors_creek_unit_and_south_sulphur_unit_state_park', 'Cooper Lake State Park - includes Doctors Creek Unit and South Sulphur Unit', 'Hiked 3 trails at Cooper Lake State Park - includes Doctors Creek Unit and South Sulphur Unit', 'TX'),
('copper_breaks_state_park_state_park', 'Copper Breaks State Park', 'Hiked 3 trails at Copper Breaks State Park', 'TX'),
('daingerfield_state_park_state_park', 'Daingerfield State Park', 'Hiked 3 trails at Daingerfield State Park', 'TX'),
('davis_mountains_state_park_state_park', 'Davis Mountains State Park', 'Hiked 3 trails at Davis Mountains State Park', 'TX'),
('devils_river_state_natural_area__includes_dan_allen_hughes_unit_and_del_norte_unit_state_park', 'Devils River State Natural Area - includes Dan Allen Hughes Unit and Del Norte Unit', 'Hiked 3 trails at Devils River State Natural Area - includes Dan Allen Hughes Unit and Del Norte Unit', 'TX'),
('devils_sinkhole_state_natural_area_state_park', 'Devil''s Sinkhole State Natural Area', 'Hiked 3 trails at Devil''s Sinkhole State Natural Area', 'TX'),
('dinosaur_valley_state_park_state_park', 'Dinosaur Valley State Park', 'Hiked 3 trails at Dinosaur Valley State Park', 'TX'),
('eisenhower_state_park_state_park', 'Eisenhower State Park', 'Hiked 3 trails at Eisenhower State Park', 'TX'),
('enchanted_rock_state_natural_area_state_park', 'Enchanted Rock State Natural Area', 'Hiked 3 trails at Enchanted Rock State Natural Area', 'TX'),
('estero_llano_grande_state_park_state_park', 'Estero Llano Grande State Park', 'Hiked 3 trails at Estero Llano Grande State Park', 'TX'),
('falcon_state_park_state_park', 'Falcon State Park', 'Hiked 3 trails at Falcon State Park', 'TX'),
('fort_boggy_state_park_state_park', 'Fort Boggy State Park', 'Hiked 3 trails at Fort Boggy State Park', 'TX'),
('fort_leaton_state_historic_site_state_park', 'Fort Leaton State Historic Site', 'Hiked 3 trails at Fort Leaton State Historic Site', 'TX'),
('fort_parker_state_park_state_park', 'Fort Parker State Park', 'Hiked 3 trails at Fort Parker State Park', 'TX'),
('fort_richardson_state_park_historic_site_and_lost_creek_reservoir_state_trailway_state_park', 'Fort Richardson State Park, Historic Site, and Lost Creek Reservoir State Trailway', 'Hiked 3 trails at Fort Richardson State Park, Historic Site, and Lost Creek Reservoir State Trailway', 'TX'),
('franklin_mountains_state_park_state_park', 'Franklin Mountains State Park', 'Hiked 3 trails at Franklin Mountains State Park', 'TX'),
('galveston_island_state_park_state_park', 'Galveston Island State Park', 'Hiked 3 trails at Galveston Island State Park', 'TX'),
('garner_state_park_state_park', 'Garner State Park', 'Hiked 3 trails at Garner State Park', 'TX'),
('goliad_state_park_and_historic_site__includes_mission_rosario_state_historic_site_and_zaragoza_birthplace_state_historic_site_state_park', 'Goliad State Park and Historic Site - includes Mission Rosario State Historic Site and Zaragoza Birthplace State Historic Site', 'Hiked 3 trails at Goliad State Park and Historic Site - includes Mission Rosario State Historic Site and Zaragoza Birthplace State Historic Site', 'TX'),
('goose_island_state_park_state_park', 'Goose Island State Park', 'Hiked 3 trails at Goose Island State Park', 'TX'),
('government_canyon_state_natural_area_state_park', 'Government Canyon State Natural Area', 'Hiked 3 trails at Government Canyon State Natural Area', 'TX'),
('guadalupe_river_state_park_state_park', 'Guadalupe River State Park', 'Hiked 3 trails at Guadalupe River State Park', 'TX'),
('hill_country_state_natural_area_state_park', 'Hill Country State Natural Area', 'Hiked 3 trails at Hill Country State Natural Area', 'TX'),
('honey_creek_state_natural_area_state_park', 'Honey Creek State Natural Area', 'Hiked 3 trails at Honey Creek State Natural Area', 'TX'),
('hueco_tanks_state_park_and_historic_site_state_park', 'Hueco Tanks State Park and Historic Site', 'Hiked 3 trails at Hueco Tanks State Park and Historic Site', 'TX'),
('huntsville_state_park_state_park', 'Huntsville State Park', 'Hiked 3 trails at Huntsville State Park', 'TX'),
('inks_lake_state_park_state_park', 'Inks Lake State Park', 'Hiked 3 trails at Inks Lake State Park', 'TX'),
('kickapoo_cavern_state_park_state_park', 'Kickapoo Cavern State Park', 'Hiked 3 trails at Kickapoo Cavern State Park', 'TX'),
('lake_arrowhead_state_park_state_park', 'Lake Arrowhead State Park', 'Hiked 3 trails at Lake Arrowhead State Park', 'TX'),
('lake_bob_sandlin_state_park_state_park', 'Lake Bob Sandlin State Park', 'Hiked 3 trails at Lake Bob Sandlin State Park', 'TX'),
('lake_brownwood_state_park_state_park', 'Lake Brownwood State Park', 'Hiked 3 trails at Lake Brownwood State Park', 'TX'),
('lake_casa_blanca_international_state_park_state_park', 'Lake Casa Blanca International State Park', 'Hiked 3 trails at Lake Casa Blanca International State Park', 'TX'),
('lake_colorado_city_state_park_state_park', 'Lake Colorado City State Park', 'Hiked 3 trails at Lake Colorado City State Park', 'TX'),
('lake_corpus_christi_state_park_state_park', 'Lake Corpus Christi State Park', 'Hiked 3 trails at Lake Corpus Christi State Park', 'TX'),
('lake_livingston_state_park_state_park', 'Lake Livingston State Park', 'Hiked 3 trails at Lake Livingston State Park', 'TX'),
('lake_mineral_wells_state_park__trailway_state_park', 'Lake Mineral Wells State Park & Trailway', 'Hiked 3 trails at Lake Mineral Wells State Park & Trailway', 'TX'),
('lake_somerville_state_park_and_trailway__includes_birch_creek_unit_and_nails_creek_unit_state_park', 'Lake Somerville State Park and Trailway - includes Birch Creek Unit and Nails Creek Unit', 'Hiked 3 trails at Lake Somerville State Park and Trailway - includes Birch Creek Unit and Nails Creek Unit', 'TX'),
('lake_tawakoni_state_park_state_park', 'Lake Tawakoni State Park', 'Hiked 3 trails at Lake Tawakoni State Park', 'TX'),
('lake_whitney_state_park_state_park', 'Lake Whitney State Park', 'Hiked 3 trails at Lake Whitney State Park', 'TX'),
('lockhart_state_park_state_park', 'Lockhart State Park', 'Hiked 3 trails at Lockhart State Park', 'TX'),
('longhorn_cavern_state_park_state_park', 'Longhorn Cavern State Park', 'Hiked 3 trails at Longhorn Cavern State Park', 'TX'),
('lost_maples_state_natural_area_state_park', 'Lost Maples State Natural Area', 'Hiked 3 trails at Lost Maples State Natural Area', 'TX'),
('lyndon_b_johnson_state_park_and_historic_site__includes_sauerbeckmann_living_history_farm_state_park', 'Lyndon B. Johnson State Park and Historic Site - includes Sauer-Beckmann Living History Farm', 'Hiked 3 trails at Lyndon B. Johnson State Park and Historic Site - includes Sauer-Beckmann Living History Farm', 'TX'),
('martin_creek_lake_state_park_state_park', 'Martin Creek Lake State Park', 'Hiked 3 trails at Martin Creek Lake State Park', 'TX'),
('martin_dies_jr_state_park_state_park', 'Martin Dies, Jr. State Park', 'Hiked 3 trails at Martin Dies, Jr. State Park', 'TX'),
('mckinney_falls_state_park_state_park', 'McKinney Falls State Park', 'Hiked 3 trails at McKinney Falls State Park', 'TX'),
('meridian_state_park_state_park', 'Meridian State Park', 'Hiked 3 trails at Meridian State Park', 'TX'),
('mission_tejas_state_park_state_park', 'Mission Tejas State Park', 'Hiked 3 trails at Mission Tejas State Park', 'TX'),
('monahans_sandhills_state_park_state_park', 'Monahans Sandhills State Park', 'Hiked 3 trails at Monahans Sandhills State Park', 'TX'),
('mother_neff_state_park_state_park', 'Mother Neff State Park', 'Hiked 3 trails at Mother Neff State Park', 'TX'),
('mustang_island_state_park_state_park', 'Mustang Island State Park', 'Hiked 3 trails at Mustang Island State Park', 'TX'),
('old_tunnel_state_park_state_park', 'Old Tunnel State Park', 'Hiked 3 trails at Old Tunnel State Park', 'TX'),
('palmetto_state_park_state_park', 'Palmetto State Park', 'Hiked 3 trails at Palmetto State Park', 'TX'),
('palo_duro_canyon_state_park_state_park', 'Palo Duro Canyon State Park', 'Hiked 3 trails at Palo Duro Canyon State Park', 'TX'),
('palo_pinto_mountains_state_park_under_development_state_park', 'Palo Pinto Mountains State Park (under development)', 'Hiked 3 trails at Palo Pinto Mountains State Park (under development)', 'TX'),
('pedernales_falls_state_park_state_park', 'Pedernales Falls State Park', 'Hiked 3 trails at Pedernales Falls State Park', 'TX'),
('possum_kingdom_state_park_state_park', 'Possum Kingdom State Park', 'Hiked 3 trails at Possum Kingdom State Park', 'TX'),
('purtis_creek_state_park_state_park', 'Purtis Creek State Park', 'Hiked 3 trails at Purtis Creek State Park', 'TX'),
('ray_roberts_lake_state_park__includes_isle_du_bois_unit_johnson_branch_unit_jordan_park_unit_ray_roberts_greenbelt_corridor_and_sanger_marina_unit_state_park', 'Ray Roberts Lake State Park - includes Isle du Bois Unit, Johnson Branch Unit, Jordan Park Unit, Ray Roberts Greenbelt Corridor, and Sanger Marina Unit', 'Hiked 3 trails at Ray Roberts Lake State Park - includes Isle du Bois Unit, Johnson Branch Unit, Jordan Park Unit, Ray Roberts Greenbelt Corridor, and Sanger Marina Unit', 'TX'),
('resaca_de_la_palma_state_park_state_park', 'Resaca de la Palma State Park', 'Hiked 3 trails at Resaca de la Palma State Park', 'TX'),
('san_angelo_state_park_state_park', 'San Angelo State Park', 'Hiked 3 trails at San Angelo State Park', 'TX'),
('sea_rim_state_park_state_park', 'Sea Rim State Park', 'Hiked 3 trails at Sea Rim State Park', 'TX'),
('seminole_canyon_state_park_and_historic_site_state_park', 'Seminole Canyon State Park and Historic Site', 'Hiked 3 trails at Seminole Canyon State Park and Historic Site', 'TX'),
('sheldon_lake_state_park_and_environmental_learning_center_state_park', 'Sheldon Lake State Park and Environmental Learning Center', 'Hiked 3 trails at Sheldon Lake State Park and Environmental Learning Center', 'TX'),
('south_llano_river_state_park_state_park', 'South Llano River State Park', 'Hiked 3 trails at South Llano River State Park', 'TX'),
('stephen_f_austin_state_park_state_park', 'Stephen F. Austin State Park', 'Hiked 3 trails at Stephen F. Austin State Park', 'TX'),
('tyler_state_park_state_park', 'Tyler State Park', 'Hiked 3 trails at Tyler State Park', 'TX'),
('village_creek_state_park_state_park', 'Village Creek State Park', 'Hiked 3 trails at Village Creek State Park', 'TX'),
('categoryaudra_state_park_on_wikimedia_commons_state_park', 'Category:Audra State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Audra State Park on Wikimedia Commons', 'WV'),
('categorybabcock_state_park_on_wikimedia_commons_state_park', 'Category:Babcock State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Babcock State Park on Wikimedia Commons', 'WV'),
('categorybeartown_state_park_on_wikimedia_commons_state_park', 'Category:Beartown State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Beartown State Park on Wikimedia Commons', 'WV'),
('categorybeech_fork_state_park_on_wikimedia_commons_state_park', 'Category:Beech Fork State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Beech Fork State Park on Wikimedia Commons', 'WV'),
('categoryberkeley_springs_state_park_on_wikimedia_commons_state_park', 'Category:Berkeley Springs State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Berkeley Springs State Park on Wikimedia Commons', 'WV'),
('categoryblackwater_falls_state_park_on_wikimedia_commons_state_park', 'Category:Blackwater Falls State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Blackwater Falls State Park on Wikimedia Commons', 'WV'),
('categoryblennerhassett_island_historical_state_park_on_wikimedia_commons_state_park', 'Category:Blennerhassett Island Historical State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Blennerhassett Island Historical State Park on Wikimedia Commons', 'WV'),
('categorybluestone_state_park_on_wikimedia_commons_state_park', 'Category:Bluestone State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Bluestone State Park on Wikimedia Commons', 'WV'),
('categorycacapon_resort_state_park_on_wikimedia_commons_state_park', 'Category:Cacapon Resort State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Cacapon Resort State Park on Wikimedia Commons', 'WV'),
('categorycamp_creek_state_park_on_wikimedia_commons_state_park', 'Category:Camp Creek State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Camp Creek State Park on Wikimedia Commons', 'WV'),
('categorycanaan_valley_resort_state_park_on_wikimedia_commons_state_park', 'Category:Canaan Valley Resort State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Canaan Valley Resort State Park on Wikimedia Commons', 'WV'),
('categorycarnifex_ferry_battlefield_state_park_on_wikimedia_commons_state_park', 'Category:Carnifex Ferry Battlefield State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Carnifex Ferry Battlefield State Park on Wikimedia Commons', 'WV'),
('categorycass_scenic_railroad_state_park_on_wikimedia_commons_state_park', 'Category:Cass Scenic Railroad State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Cass Scenic Railroad State Park on Wikimedia Commons', 'WV'),
('categorycathedral_state_park_on_wikimedia_commons_state_park', 'Category:Cathedral State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Cathedral State Park on Wikimedia Commons', 'WV'),
('categorycedar_creek_state_park_on_wikimedia_commons_state_park', 'Category:Cedar Creek State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Cedar Creek State Park on Wikimedia Commons', 'WV'),
('categorychief_logan_state_park_on_wikimedia_commons_state_park', 'Category:Chief Logan State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Chief Logan State Park on Wikimedia Commons', 'WV'),
('categorydroop_mountain_battlefield_state_park_on_wikimedia_commons_state_park', 'Category:Droop Mountain Battlefield State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Droop Mountain Battlefield State Park on Wikimedia Commons', 'WV'),
('categoryelk_river_trail_on_wikimedia_commons_state_park', 'Category:Elk River Trail on Wikimedia Commons', 'Hiked 3 trails at Category:Elk River Trail on Wikimedia Commons', 'WV'),
('categoryfairfax_stone_historical_monument_state_park_on_wikimedia_commons_state_park', 'Category:Fairfax Stone Historical Monument State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Fairfax Stone Historical Monument State Park on Wikimedia Commons', 'WV'),
('categorygreenbrier_river_trail_on_wikimedia_commons_state_park', 'Category:Greenbrier River Trail on Wikimedia Commons', 'Hiked 3 trails at Category:Greenbrier River Trail on Wikimedia Commons', 'WV'),
('categoryhawks_nest_state_park_on_wikimedia_commons_state_park', 'Category:Hawks Nest State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Hawks Nest State Park on Wikimedia Commons', 'WV'),
('categoryholly_river_state_park_on_wikimedia_commons_state_park', 'Category:Holly River State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Holly River State Park on Wikimedia Commons', 'WV'),
('categorylittle_beaver_state_park_on_wikimedia_commons_state_park', 'Category:Little Beaver State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Little Beaver State Park on Wikimedia Commons', 'WV'),
('categorylost_river_state_park_on_wikimedia_commons_state_park', 'Category:Lost River State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Lost River State Park on Wikimedia Commons', 'WV'),
('categorymoncove_lake_state_park_on_wikimedia_commons_state_park', 'Category:Moncove Lake State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Moncove Lake State Park on Wikimedia Commons', 'WV'),
('categorynorth_bend_state_park_on_wikimedia_commons_state_park', 'Category:North Bend State Park on Wikimedia Commons', 'Hiked 3 trails at Category:North Bend State Park on Wikimedia Commons', 'WV'),
('categorynorth_bend_rail_trail_state_park_on_wikimedia_commons_state_park', 'Category:North Bend Rail Trail State Park on Wikimedia Commons', 'Hiked 3 trails at Category:North Bend Rail Trail State Park on Wikimedia Commons', 'WV'),
('categorypinnacle_rock_state_park_on_wikimedia_commons_state_park', 'Category:Pinnacle Rock State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Pinnacle Rock State Park on Wikimedia Commons', 'WV'),
('categorypipestem_resort_state_park_on_wikimedia_commons_state_park', 'Category:Pipestem Resort State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Pipestem Resort State Park on Wikimedia Commons', 'WV'),
('categorypricketts_fort_state_park_on_wikimedia_commons_state_park', 'Category:Prickett''s Fort State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Prickett''s Fort State Park on Wikimedia Commons', 'WV'),
('categorystonewall_jackson_lake_state_park_on_wikimedia_commons_state_park', 'Category:Stonewall Jackson Lake State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Stonewall Jackson Lake State Park on Wikimedia Commons', 'WV'),
('categorytomlinson_run_state_park_on_wikimedia_commons_state_park', 'Category:Tomlinson Run State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Tomlinson Run State Park on Wikimedia Commons', 'WV'),
('categorytuendiewei_state_park_on_wikimedia_commons_state_park', 'Category:Tu-Endie-Wei State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Tu-Endie-Wei State Park on Wikimedia Commons', 'WV'),
('categorytwin_falls_resort_state_park_on_wikimedia_commons_state_park', 'Category:Twin Falls Resort State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Twin Falls Resort State Park on Wikimedia Commons', 'WV'),
('categorytygart_lake_state_park_on_wikimedia_commons_state_park', 'Category:Tygart Lake State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Tygart Lake State Park on Wikimedia Commons', 'WV'),
('categoryvalley_falls_state_park_on_wikimedia_commons_state_park', 'Category:Valley Falls State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Valley Falls State Park on Wikimedia Commons', 'WV'),
('categorywatoga_state_park_on_wikimedia_commons_state_park', 'Category:Watoga State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Watoga State Park on Wikimedia Commons', 'WV'),
('categorywatters_smith_memorial_state_park_on_wikimedia_commons_state_park', 'Category:Watters Smith Memorial State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Watters Smith Memorial State Park on Wikimedia Commons', 'WV'),
('categorybooker_t_washington_state_park_west_virginia_on_wikimedia_commons_state_park', 'Category:Booker T. Washington State Park (West Virginia) on Wikimedia Commons', 'Hiked 3 trails at Category:Booker T. Washington State Park (West Virginia) on Wikimedia Commons', 'WV'),
('categorygrandview_state_park_on_wikimedia_commons_state_park', 'Category:Grandview State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Grandview State Park on Wikimedia Commons', 'WV'),
('categorygrave_creek_mound_on_wikimedia_commons_state_park', 'Category:Grave Creek Mound on Wikimedia Commons', 'Hiked 3 trails at Category:Grave Creek Mound on Wikimedia Commons', 'WV'),
('categoryjames_rumsey_monument_on_wikimedia_commons_state_park', 'Category:James Rumsey Monument on Wikimedia Commons', 'Hiked 3 trails at Category:James Rumsey Monument on Wikimedia Commons', 'WV'),
('categorymingo_oak_on_wikimedia_commons_state_park', 'Category:Mingo Oak on Wikimedia Commons', 'Hiked 3 trails at Category:Mingo Oak on Wikimedia Commons', 'WV'),
('categorymont_chateau_state_park_on_wikimedia_commons_state_park', 'Category:Mont Chateau State Park on Wikimedia Commons', 'Hiked 3 trails at Category:Mont Chateau State Park on Wikimedia Commons', 'WV'),
('categorymorgan_morgan_monument_on_wikimedia_commons_state_park', 'Category:Morgan Morgan Monument on Wikimedia Commons', 'Hiked 3 trails at Category:Morgan Morgan Monument on Wikimedia Commons', 'WV');